[build-system]
requires = ["setuptools>=69.0.0", "wheel>=0.42.0"]
build-backend = "setuptools.build_meta"

[project]
name = "amazon-multimodal-product-assistant"
version = "0.1.0"
description = "Amazon E-commerce Visual Assistant"
requires-python = ">=3.10"
